_target_: pytorch_lightning.Trainer

accelerator: gpu
devices: 1
min_epochs: 1
max_epochs: 100

enable_progress_bar: True

detect_anomaly: True
log_every_n_steps: 10
track_grad_norm: -1  # -1: disabled; 2: track 2-norm

# number of validation steps to execute at the beginning of the training
# num_sanity_val_steps: 0

# ckpt path
resume_from_checkpoint: null

enable_checkpointing: True
