_target_: torchpanic.modules.standard.StandardModule
lr: 0.003607382027438678
weight_decay: 1.1061692016959738e-05
output_penalty_weight: 0.0
num_classes: ${datamodule.metadata.num_classes}
validation_metric: 'val/bacc_best'

net:
  _target_: torchpanic.models.daft.DAFT
  in_channels: ${datamodule.metadata.num_channels}
  in_tabular: 41
  n_outputs: ${datamodule.metadata.num_classes}
  n_basefilters: 32
  filmblock_args:
    location: 3
    scale: True
    shift: True
    bottleneck_dim: 12
  idx_tabular_has_missing:
    - 3  # abeta
    - 4  # tau
    - 5  # ptau
    - 10  # all categorical, except gender
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
    - 32
    - 33
    - 34
    - 35
    - 36
    - 37
    - 38
    - 39
    - 40
